export const defaultFromLanguage = "AUTO";

export const fromLanguages = {
	AUTO: "Detect language",
	BG: "Bulgarian",
	CS: "Czech",
	DA: "Danish",
	DE: "German",
	EL: "Greek",
	EN: "English",
	ES: "Spanish",
	ET: "Estonian",
	FI: "Finnish",
	FR: "French",
	HU: "Hungarian",
	ID: "Indonesian",
	IT: "Italian",
	JA: "Japanese",
	LT: "Lithuanian",
	LV: "Latvian",
	NL: "Dutch",
	PL: "Polish",
	PT: "Portuguese",
	RO: "Romanian",
	RU: "Russian",
	SK: "Slovak",
	SL: "Slovenian",
	SV: "Swedish",
	TR: "Turkish",
	UK: "Ukrainian",
	ZH: "Chinese",
};
